config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :loan_departments
  resources :account_departments
  root 'banks#index'
  resources :branches
  resources :banks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'banks#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/branch.rb
# frozen_string_literal: true

class Branch < ApplicationRecord
  belongs_to :bank
  has_one :account_department, dependent: :destroy
  has_one :loan_department, dependent: :destroy
  accepts_nested_attributes_for :account_department
  accepts_nested_attributes_for :loan_department
end

app/controllers/branches_controller.rb
# frozen_string_literal: true

class BranchesController < ApplicationController
  before_action :set_branch, only: %i[show edit update destroy]

  # GET /branches or /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1 or /branches/1.json
  def show; end

  # GET /branches/new
  def new
    @branch = Branch.new
    @branch.build_account_department
    @branch.build_loan_department
  end

  # GET /branches/1/edit
  def edit
    @branch.build_account_department
    @branch.build_loan_department
  end

  # POST /branches or /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_branch
    @branch = Branch.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def branch_params
    params.require(:branch).permit(:branch_name, :branch_address, :bank_id,
                                   loan_department_attributes: %i[loan_type loan_amount], account_department_attributes: %i[account_type account_no account_balance])
  end
end

app/helpers/branches_helper.rb
# frozen_string_literal: true

module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_with(model: branch) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
        <% branch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :branch_name, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :branch_name, value: current_bank.bank_name, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :branch_address, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :branch_address, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :Bank_Code, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :bank_id, value: current_bank.id, class: "col-sm-6" %>
  </div>
  <%= form.fields_for :account_department do |account| %>
    <div class="mb-3 row">
      <%= account.label :account_type, class: "col-sm-2 col-form-label" %>
      <%= account.text_field :account_type, class: "col-sm-6" %>
    </div>

    <div class="mb-3 row">
      <%= account.label :account_no, class: "col-sm-2 col-form-label" %>
      <%= account.text_field :account_no, class: "col-sm-6" %>
    </div>

    <div class="mb-3 row">
      <%= account.label :account_balance, class: "col-sm-2 col-form-label" %>
      <%= account.text_field :account_balance, class: "col-sm-6" %>
    </div>
  <% end %>
  <%= form.fields_for :loan_department do |loan| %>
    <div class="mb-3 row">
      <%= loan.label :loan_type, class: "col-sm-2 col-form-label" %>
      <%= loan.text_field :loan_type, class: "col-sm-6" %>
    </div>

    <div class="mb-3 row">
      <%= loan.label :loan_amount, class: "col-sm-2 col-form-label" %>
      <%= loan.text_field :loan_amount, class: "col-sm-6" %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary"%>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<% if current_bank %>
	<%= render 'form', branch: @branch %>
	<%= link_to 'Show', @branch %> |
	<%= link_to 'Back', branches_path %>
<% end %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<br>

<table class="table">
  <thead class="table-secondary">
    <tr>
      <th scope="col">Branch name</th>
      <th scope="col">Branch address</th>
      <th scope="col">Bank Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <% @branches.each do |branch| %>
        <% if branch.bank == current_bank %>
        <tr>
          <td><%= branch.branch_name %></td>
          <td><%= branch.branch_address %></td>
          <td><%= branch.bank_id %></td>
          <td><button type="button" class="btn btn-outline-secondary"><%= link_to 'Show', branch %></button></td>
          <td><button type="button" class="btn btn-outline-secondary"><%= link_to 'Edit', edit_branch_path(branch) %></button></td>
          <td><button type="button" class="btn btn-outline-secondary"><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-dark"><%= link_to 'New Branch', new_branch_path %></button>
<button type="button" class="btn btn-dark"><%= link_to 'Back', banks_path %></button>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path, class: "btn btn-outline-secondary" %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

	<p>
	  <strong>Branch name:</strong>
	  <%= @branch.branch_name %>
	</p>

	<p>
	  <strong>Branch address:</strong>
	  <%= @branch.branch_address %>
	</p>

	<p>
	  <strong>Bank:</strong>
	  <%= @branch.bank_id %>
	</p>
	
	

	<%= link_to 'Edit', edit_branch_path(@branch), class: "btn btn-outline-secondary" %> 
	<%= link_to 'Back', branches_path, class: "btn btn-outline-secondary" %>