config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :loan_departments
  resources :account_departments
  root 'banks#index'
  resources :branches
  resources :banks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'banks#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/account_department.rb
# frozen_string_literal: true

class AccountDepartment < ApplicationRecord
  belongs_to :branch
end

app/controllers/account_departments_controller.rb
# frozen_string_literal: true

class AccountDepartmentsController < ApplicationController
  before_action :set_account_department, only: %i[show edit update destroy]

  # GET /account_departments or /account_departments.json
  def index
    @account_departments = AccountDepartment.all
  end

  # GET /account_departments/1 or /account_departments/1.json
  def show; end

  # GET /account_departments/new
  def new
    @account_department = AccountDepartment.new
  end

  # GET /account_departments/1/edit
  def edit; end

  # POST /account_departments or /account_departments.json
  def create
    @account_department = AccountDepartment.new(account_department_params)

    respond_to do |format|
      if @account_department.save
        format.html { redirect_to @account_department, notice: 'Account department was successfully created.' }
        format.json { render :show, status: :created, location: @account_department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_departments/1 or /account_departments/1.json
  def update
    respond_to do |format|
      if @account_department.update(account_department_params)
        format.html { redirect_to @account_department, notice: 'Account department was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_departments/1 or /account_departments/1.json
  def destroy
    @account_department.destroy
    respond_to do |format|
      format.html { redirect_to account_departments_url, notice: 'Account department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account_department
    @account_department = AccountDepartment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_department_params
    params.require(:account_department).permit(:account_type, :account_no, :account_balance, :branch_id)
  end
end

app/helpers/account_departments_helper.rb
# frozen_string_literal: true

module AccountDepartmentsHelper
end

app/views/account_departments/_form.html.erb
<center>
  <%= form_with(model: account_department) do |form| %>
  <% if account_department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_department.errors.count, "error") %> prohibited this account_department from being saved:</h2>

      <ul>
        <% account_department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :account_type, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :account_type, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :account_no, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :account_no, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :account_balance, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :account_balance, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :branch_id, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :branch_id, class: "col-sm-6" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary"%>
  </div>
<% end %>
</center>

app/views/account_departments/edit.html.erb
<h1>Editing Account Department</h1>

<%= render 'form', account_department: @account_department %>
<center>
<%= link_to 'Show', @account_department, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', account_departments_path, class: "btn btn-outline-secondary" %>
</center>

app/views/account_departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Departments</h1>

<table class="table">
  <thead class="table-secondary">
    <tr>
      <th>Account type</th>
      <th>Account no</th>
      <th>Account balance</th>
      <th>Branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_departments.each do |account_department| %>
      <tr>
        <td><%= account_department.account_type %></td>
        <td><%= account_department.account_no %></td>
        <td><%= account_department.account_balance %></td>
        <td><%= account_department.branch_id %></td>
        <td><%= link_to 'Show', account_department, class: "btn btn-outline-secondary"  %></td>
        <td><%= link_to 'Edit', edit_account_department_path(account_department), class: "btn btn-outline-secondary" %></td>
        <td><%= link_to 'Destroy', account_department, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/account_departments/new.html.erb
<h1>New Account Department</h1>

<%= render 'form', account_department: @account_department %>

<%= link_to 'Back', account_departments_path, class: "btn btn-outline-secondary" %>

app/views/account_departments/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<p>
  <strong>Account type:</strong>
  <%= @account_department.account_type %>
</p>

<p>
  <strong>Account no:</strong>
  <%= @account_department.account_no %>
</p>

<p>
  <strong>Account balance:</strong>
  <%= @account_department.account_balance %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @account_department.branch_id %>
</p>

<%= link_to 'Edit', edit_account_department_path(@account_department), class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', account_departments_path, class: "btn btn-outline-secondary" %>
</center>