config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :loan_departments
  resources :account_departments
  root 'banks#index'
  resources :branches
  resources :banks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'banks#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/bank.rb
# frozen_string_literal: true

class Bank < ApplicationRecord
  has_secure_password
  has_many :branches, dependent: :destroy

  validates :bank_name, presence: true, uniqueness: true

  mount_uploader :avatar, BankImgUploader
end

app/controllers/banks_controller.rb
# frozen_string_literal: true

class BanksController < ApplicationController
  before_action :set_bank, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create index]
  # GET /banks or /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1 or /banks/1.json
  def show; end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
    @banks = Bank.find(params[:id])
  end

  # POST /banks or /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bank
    @bank = Bank.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bank_params
    params.require(:bank).permit(:bank_name, :head_office, :password, :password_confirmation, :avatar)
  end
end

app/helpers/banks_helper.rb
# frozen_string_literal: true

module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_with(model: bank) do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
        <% bank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :bank_name, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :bank_name, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :head_office, class: "col-sm-2 col-form-label"  %>
    <%= form.text_field :head_office, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :password, class: "col-sm-2 col-form-label" %>
    <%= form.password_field :password, class: "col-sm-6" %>
  </div>

  <div class="mb-3 row">
    <%= form.label :password_confirmation, class: "col-sm-2 col-form-label" %>
    <%= form.password_field :password_confirmation, class: "col-sm-6" %>
  </div>

  <div class="mb-3">
    <%= form.label :bank_image, class: "col-sm-2 col-form-label" %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
  
<% end %>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Show', @bank, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', banks_path, class: "btn btn-outline-secondary" %>

app/views/banks/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Bank management system</h1></center>


 <% if current_bank %>


<table class="table">
  <thead class="table-secondary">
    <tr>
      <th>name</th>
      <th>address</th>
      <th>image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <% if bank == current_bank %>
      <tr>
        <td><%= bank.bank_name %></td>
        <td><%= bank.head_office %></td>
        <td><img src="<%= bank.avatar %>" width="100" height="100"></td>
        <td><%= link_to "Show", bank, class: "btn btn-outline-secondary" %></td>
        <td><%= link_to "Edit", edit_bank_path(bank), class: "btn btn-outline-secondary" %></td>
        <td><%= link_to "Destroy", bank, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-secondary" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
   
<br>
<% end %>

app/views/banks/new.html.erb
<center>

	<h1>New Bank</h1><br>

	<%= render 'form', bank: @bank %>

	<%= link_to 'Back', banks_path, class: "btn btn-outline-secondary" %>
</center>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank name:</strong>
  <%= @bank.bank_name %>
</p>

<p>
  <strong>Head office:</strong>
  <%= @bank.head_office %>
</p>

<p>
  <strong>bank image:</strong>
  <%= @bank.avatar %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank), class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', banks_path, class: "btn btn-outline-secondary" %>